import type { Booster, Crop, DashboardMetrics } from "@/types";

/** Cosechas tokenizadas — datos realistas Costa Rica */
export const MOCK_CROPS: Crop[] = [
  {
    id: "1",
    cropName: "Café",
    region: "Tarrazú",
    farmer: "Don Carlos Mora",
    tokensAvailable: 620,
    totalTokens: 1000,
    tokensSold: 380,
    pricePerToken: 2.5,
    priceLabel: "$2.50 USDC",
    harvestDate: "2026-03-15",
    status: "Activa",
    lat: 9.6539,
    lng: -84.0297,
  },
  {
    id: "2",
    cropName: "Frijol",
    region: "Brunca (Pérez Zeledón)",
    farmer: "Cooperativa Los Ángeles",
    tokensAvailable: 210,
    totalTokens: 500,
    tokensSold: 290,
    pricePerToken: 1.2,
    priceLabel: "$1.20 USDC",
    harvestDate: "2026-02-28",
    status: "Activa",
    lat: 9.3647,
    lng: -83.6313,
  },
  {
    id: "3",
    cropName: "Cacao",
    region: "Limón (Talamanca)",
    farmer: "María Fernández",
    tokensAvailable: 95,
    totalTokens: 300,
    tokensSold: 205,
    pricePerToken: 4.8,
    priceLabel: "$4.80 USDC",
    harvestDate: "2026-04-10",
    status: "Activa",
    lat: 9.5683,
    lng: -82.9757,
  },
  {
    id: "4",
    cropName: "Maíz criollo",
    region: "Guanacaste (Nicoya)",
    farmer: "Familia Solano",
    tokensAvailable: 140,
    totalTokens: 200,
    tokensSold: 60,
    pricePerToken: 0.9,
    priceLabel: "$0.90 USDC",
    harvestDate: "2026-01-20",
    status: "Validada",
    lat: 10.1483,
    lng: -85.452,
  },
];

export const MOCK_BOOSTERS: Booster[] = [
  {
    id: 1,
    boosterType: "Dron NDVI",
    parcel: "Café Tarrazú — Don Carlos Mora",
    amount: 850,
    amountLabel: "$850 USDC",
    status: "Activo",
    provider: "AgroVuelo CR",
    cropType: "cafe",
    region: "Tarrazú",
  },
  {
    id: 2,
    boosterType: "Riego inteligente",
    parcel: "Frijol Brunca — Cooperativa Los Ángeles",
    amount: 1200,
    amountLabel: "$1,200 USDC",
    status: "Pendiente",
    provider: "HidroSur S.A.",
    cropType: "frijol",
    region: "Brunca",
  },
  {
    id: 3,
    boosterType: "Semillas certificadas",
    parcel: "Cacao Bribri Limón — María Fernández",
    amount: 600,
    amountLabel: "$600 USDC",
    status: "Pendiente",
    provider: "Semillas del Caribe",
    cropType: "cacao",
    region: "Limón",
  },
  {
    id: 4,
    boosterType: "Sensores IoT",
    parcel: "Maíz criollo Guanacaste — Familia Solano",
    amount: 420,
    amountLabel: "$420 USDC",
    status: "Completado",
    provider: "CampoConecta",
    cropType: "maiz",
    region: "Guanacaste",
  },
  {
    id: 5,
    boosterType: "Certificación orgánica",
    parcel: "Café Tarrazú — Don Carlos Mora",
    amount: 1500,
    amountLabel: "$1,500 USDC",
    status: "Activo",
    provider: "EcoCert LATAM",
    cropType: "cafe",
    region: "Tarrazú",
  },
];

export const MOCK_METRICS: DashboardMetrics = {
  activeCrops: 4,
  capitalInvestedUsdc: 12450,
  averageYieldPct: 82.5,
  activeBoosters: 2,
};
